test:
  adapter: postgresql
  database: compete_test
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: compete_development
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql